### ISSUE TITLE
Парабола.

### ISSUE THREAD

**Issue by Screeki** [Screeki/WPF2021#2]

**Comment by Screeki** [comment]
@justjune

**Comment by justjune** [comment]
См. Успеваемостью

**Comment by Screeki** [comment]
![image](https://user-images.githubusercontent.com/49313741/110364237-57525d80-8065-11eb-9056-b13811ef5db3.png)
Я правильно понял, что у нас на одну неделю то что я обвёл разными цветами?

**Comment by Screeki** [comment]
Можете закрывать после ответа

**Comment by justjune** [comment]
Да.
